
title: Walker Lima - Clinica de Psicologia
email: walkerlima@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Trazendo
#baseurl: ""
url: "https://linktr.ee/profwalkerlimaf" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
